version: '3'

services:
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - monitoring

  your-app:
    image: your-app-image
    ports:
      - 'docker run -itd -p 8080:8080 --name finance-me rohith2703/bankingcapstone:1.0'
    networks:
      - monitoring

networks:
  monitoring:

